
spring:
  application:
    name: empleados-service
  
  data:
    mongodb:
      #URI proporcionado por mongodb atlas para conectarse a la BDD  
      uri: 
      #Nombre de la BDD
      database: 
     
server:
  port: 7102
  
#Eureka Configuration Properties
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:7100/eureka
      
      
  